name 'aggressivex-bind'
version '0.5.1'
source 'git://github.com/aggressivex/puppet-bind.git'
author 'Luis M. Hdez - Aggressivex NetWorks'
license 'MIT'
summary 'Bind module'
description 'Bind module'
project_page 'http://github.com/aggressivex/puppet-bind'